name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js, npm and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install

      - name: Package all
        run: yarn build:all

      - name: Clean
        run: yarn clean

      - name: Create a release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  createReleaseNote:
    runs-on: ubuntu-latest
    needs: [release]

    steps:
      - name: Set environment variables
        run: echo "VERSION=${GITHUB_REF##*/v}" >> $GITHUB_ENV

      - name: Create a release note
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: |
            ## 配布ファイル
            |OS|インストーラ|
            |-|-|
            |Windows|clara-editor-${{ env.VERSION }}.exe|
            |macOS|clara-editor-${{ env.VERSION }}.dmg|
            |Liunx|clara-editor-${{ env.VERSION }}.AppImage|
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
